-- Demo data for AI Local Food Matchmaker.
-- Safe to rerun: rows generated by this file are marked and refreshed.

begin;

delete from public.match_histories
where query_context ->> 'demo_seed' = 'true';

delete from public.reviews
where comment like '[demo_seed]%';

delete from public.group_members
where group_id = '30000000-0000-0000-0000-000000000001';

delete from public.groups
where id = '30000000-0000-0000-0000-000000000001';

insert into public.users (id, name, language, nationality)
values
  ('10000000-0000-0000-0000-000000000001', 'Demo Tourist', 'en', 'United States'),
  ('10000000-0000-0000-0000-000000000002', 'เจ้าของร้านเดโม', 'th', 'Thailand'),
  ('10000000-0000-0000-0000-000000000003', 'Yuki Tanaka', 'en', 'Japan'),
  ('10000000-0000-0000-0000-000000000004', 'Anna Schmidt', 'en', 'Germany'),
  ('10000000-0000-0000-0000-000000000005', 'Li Wei', 'en', 'China'),
  ('10000000-0000-0000-0000-000000000006', 'Nadia Hassan', 'en', 'Malaysia'),
  ('10000000-0000-0000-0000-000000000007', 'Marco Rossi', 'en', 'Italy')
on conflict (id) do update set
  name = excluded.name,
  language = excluded.language,
  nationality = excluded.nationality;

insert into public.user_preferences (
  user_id,
  food_tags,
  view_tags,
  atmosphere_tags,
  service_tags,
  place_context_tags,
  dietary_restrictions,
  allergies,
  transport_modes,
  budget_min,
  budget_max,
  max_distance_km,
  learned_preferences
)
values
  (
    '10000000-0000-0000-0000-000000000001',
    array['thai_food', 'local_food', 'spicy'],
    array['mountain_view', 'river_view'],
    array['quiet', 'photo_spot'],
    array['english_menu_available', 'tourist_friendly', 'promptpay_available'],
    array['local_hidden_gem', 'good_for_group'],
    array['no_pork'],
    array['shrimp'],
    array['taxi', 'walking'],
    60,
    250,
    18,
    '{"tagWeights":{"local_food":1.25,"quiet":1.1,"mountain_view":1.15},"demoSeed":true}'::jsonb
  ),
  (
    '10000000-0000-0000-0000-000000000003',
    array['thai_food', 'noodle', 'local_food'],
    array['river_view'],
    array['quiet'],
    array['english_menu_available', 'friendly_staff'],
    array['hidden_gem'],
    array['no_beef'],
    array[]::text[],
    array['walking', 'public_transit', 'taxi'],
    50,
    260,
    8,
    '{"tagWeights":{"noodle":1.2,"english_menu_available":1.15},"demoSeed":true}'::jsonb
  ),
  (
    '10000000-0000-0000-0000-000000000004',
    array['thai_food', 'spicy', 'vegetarian'],
    array['mountain_view'],
    array['quiet', 'family_friendly'],
    array['card_accepted', 'english_menu_available'],
    array['good_for_group'],
    array['vegetarian_possible'],
    array['peanut'],
    array['taxi', 'driving'],
    80,
    320,
    20,
    '{"tagWeights":{"vegetarian_possible":1.25,"mountain_view":1.1},"demoSeed":true}'::jsonb
  ),
  (
    '10000000-0000-0000-0000-000000000005',
    array['seafood', 'spicy', 'thai_food'],
    array['sea_view', 'photo_spot'],
    array['lively', 'family_friendly'],
    array['tourist_friendly', 'promptpay_available'],
    array['local_hidden_gem'],
    array[]::text[],
    array[]::text[],
    array['taxi', 'driving'],
    100,
    450,
    25,
    '{"tagWeights":{"seafood":1.2,"photo_spot":1.1},"demoSeed":true}'::jsonb
  ),
  (
    '10000000-0000-0000-0000-000000000006',
    array['thai_food', 'local_food'],
    array[]::text[],
    array['family_friendly'],
    array['halal_friendly', 'english_menu_available'],
    array['good_for_group'],
    array['halal_possible', 'no_pork'],
    array['shellfish'],
    array['taxi', 'public_transit'],
    70,
    260,
    15,
    '{"tagWeights":{"halal_possible":1.3,"good_for_group":1.1},"demoSeed":true}'::jsonb
  )
on conflict (user_id) do update set
  food_tags = excluded.food_tags,
  view_tags = excluded.view_tags,
  atmosphere_tags = excluded.atmosphere_tags,
  service_tags = excluded.service_tags,
  place_context_tags = excluded.place_context_tags,
  dietary_restrictions = excluded.dietary_restrictions,
  allergies = excluded.allergies,
  transport_modes = excluded.transport_modes,
  budget_min = excluded.budget_min,
  budget_max = excluded.budget_max,
  max_distance_km = excluded.max_distance_km,
  learned_preferences = excluded.learned_preferences;

insert into public.groups (id, name, owner_user_id)
values (
  '30000000-0000-0000-0000-000000000001',
  'Chiang Mai Food Gang Demo',
  '10000000-0000-0000-0000-000000000001'
);

insert into public.group_members (group_id, user_id, role)
values
  ('30000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', 'owner'),
  ('30000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000003', 'member'),
  ('30000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000004', 'member'),
  ('30000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000006', 'member');

insert into public.restaurants (
  id,
  owner_user_id,
  name_th,
  name_en,
  story_th,
  story_en,
  latitude,
  longitude,
  location,
  address_th,
  address_en,
  google_maps_url,
  opening_hours,
  timezone,
  is_open,
  view_tags,
  atmosphere_tags,
  service_tags,
  place_context_tags,
  restaurant_dietary_tags,
  price_min,
  price_max,
  price_currency,
  image_type
)
values
  (
    '20000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000002',
    'ครัวบ้านสวน',
    'Baan Suan Kitchen',
    'ร้านอาหารท้องถิ่นในสวนใกล้เนินเขา ใช้วัตถุดิบจากชุมชนและมีเมนูที่ปรับให้กินเจหรือไม่ใส่หมูได้',
    'A local garden kitchen near the hills using community ingredients, with dishes that can be adjusted for vegetarian or no-pork needs.',
    18.7883,
    98.9853,
    st_setsrid(st_makepoint(98.9853, 18.7883), 4326)::geography,
    'อำเภอเมืองเชียงใหม่ จังหวัดเชียงใหม่',
    'Mueang Chiang Mai District, Chiang Mai',
    'https://maps.google.com/?q=18.7883,98.9853',
    '[{"day":"mon","open":"09:00","close":"20:00"},{"day":"tue","open":"09:00","close":"20:00"},{"day":"wed","open":"09:00","close":"20:00"},{"day":"thu","open":"09:00","close":"20:00"},{"day":"fri","open":"09:00","close":"20:00"},{"day":"sat","open":"09:00","close":"21:00"},{"day":"sun","open":"09:00","close":"21:00"}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['mountain_view'],
    array['quiet', 'family_friendly', 'photo_spot'],
    array['friendly_staff', 'english_menu_available', 'parking_available', 'promptpay_available'],
    array['hidden_gem', 'local_hidden_gem', 'good_for_group'],
    array['vegetarian_friendly', 'vegan_friendly'],
    60,
    220,
    'THB',
    'placeholder'
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000002',
    'ริมน้ำก๋วยเตี๋ยวเรือ',
    'Rim Nam Boat Noodles',
    'ร้านก๋วยเตี๋ยวริมคลองในย่านชุมชนเก่า ราคาย่อมเยาและเดินทางง่าย',
    'A canal-side noodle shop in an old local neighborhood with affordable prices and easy access.',
    13.7563,
    100.5018,
    st_setsrid(st_makepoint(100.5018, 13.7563), 4326)::geography,
    'เขตพระนคร กรุงเทพมหานคร',
    'Phra Nakhon District, Bangkok',
    'https://maps.google.com/?q=13.7563,100.5018',
    '[{"day":"mon","open":"10:00","close":"18:00"},{"day":"tue","open":"10:00","close":"18:00"},{"day":"wed","open":"10:00","close":"18:00"},{"day":"thu","open":"10:00","close":"18:00"},{"day":"fri","open":"10:00","close":"18:00"},{"day":"sat","open":"10:00","close":"18:00"},{"day":"sun","closed":true}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['river_view'],
    array['quiet'],
    array['friendly_staff', 'cash_only', 'tourist_friendly'],
    array['hidden_gem', 'local_hidden_gem'],
    array[]::text[],
    40,
    120,
    'THB',
    'placeholder'
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    '10000000-0000-0000-0000-000000000002',
    'เจ๊น้อยอาหารเจ',
    'Auntie Noi Vegan Kitchen',
    'ร้านอาหารเจเล็ก ๆ ใกล้วัด มีเมนูผักพื้นบ้านและซุปสมุนไพร',
    'A small vegan-friendly shop near a temple serving local vegetables and herbal soups.',
    18.7930,
    98.9931,
    st_setsrid(st_makepoint(98.9931, 18.7930), 4326)::geography,
    'อำเภอเมืองเชียงใหม่ จังหวัดเชียงใหม่',
    'Mueang Chiang Mai District, Chiang Mai',
    'https://maps.google.com/?q=18.7930,98.9931',
    '[{"day":"mon","open":"08:00","close":"17:00"},{"day":"tue","open":"08:00","close":"17:00"},{"day":"wed","open":"08:00","close":"17:00"},{"day":"thu","open":"08:00","close":"17:00"},{"day":"fri","open":"08:00","close":"17:00"},{"day":"sat","open":"08:00","close":"17:00"},{"day":"sun","open":"08:00","close":"15:00"}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['temple_view'],
    array['quiet', 'family_friendly'],
    array['friendly_staff', 'cash_only'],
    array['hidden_gem', 'local_hidden_gem'],
    array['vegetarian_friendly', 'vegan_friendly'],
    45,
    160,
    'THB',
    'placeholder'
  ),
  (
    '20000000-0000-0000-0000-000000000004',
    '10000000-0000-0000-0000-000000000002',
    'ลุงแดงซีฟู้ดริมทะเล',
    'Lung Daeng Seaside Seafood',
    'ร้านซีฟู้ดท้องถิ่นติดทะเล เปิดมากว่า 20 ปี เหมาะกับครอบครัวและถ่ายรูปพระอาทิตย์ตก',
    'A seaside local seafood restaurant open for over 20 years, good for families and sunset photos.',
    7.8804,
    98.3923,
    st_setsrid(st_makepoint(98.3923, 7.8804), 4326)::geography,
    'อำเภอเมืองภูเก็ต จังหวัดภูเก็ต',
    'Mueang Phuket District, Phuket',
    'https://maps.google.com/?q=7.8804,98.3923',
    '[{"day":"mon","open":"11:00","close":"22:00"},{"day":"tue","open":"11:00","close":"22:00"},{"day":"wed","open":"11:00","close":"22:00"},{"day":"thu","open":"11:00","close":"22:00"},{"day":"fri","open":"11:00","close":"22:00"},{"day":"sat","open":"11:00","close":"23:00"},{"day":"sun","open":"11:00","close":"23:00"}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['sea_view'],
    array['family_friendly', 'photo_spot', 'lively'],
    array['parking_available', 'promptpay_available', 'tourist_friendly'],
    array['local_hidden_gem', 'good_for_group'],
    array[]::text[],
    120,
    520,
    'THB',
    'placeholder'
  ),
  (
    '20000000-0000-0000-0000-000000000005',
    '10000000-0000-0000-0000-000000000002',
    'ข้าวซอยประตูเก่า',
    'Old Gate Khao Soi',
    'ร้านข้าวซอยพื้นเมืองใกล้ประตูเมือง มีเมนูภาษาอังกฤษและเหมาะกับนักท่องเที่ยวเป็นกลุ่ม',
    'A local khao soi shop near the old city gate with English menu support and group-friendly seating.',
    18.7877,
    98.9936,
    st_setsrid(st_makepoint(98.9936, 18.7877), 4326)::geography,
    'คูเมืองเชียงใหม่ จังหวัดเชียงใหม่',
    'Old City, Chiang Mai',
    'https://maps.google.com/?q=18.7877,98.9936',
    '[{"day":"mon","open":"09:30","close":"19:30"},{"day":"tue","open":"09:30","close":"19:30"},{"day":"wed","open":"09:30","close":"19:30"},{"day":"thu","open":"09:30","close":"19:30"},{"day":"fri","open":"09:30","close":"19:30"},{"day":"sat","open":"09:30","close":"20:30"},{"day":"sun","open":"09:30","close":"20:30"}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['old_city_view'],
    array['family_friendly', 'lively'],
    array['english_menu_available', 'tourist_friendly', 'card_accepted'],
    array['good_for_group'],
    array[]::text[],
    70,
    180,
    'THB',
    'placeholder'
  )
on conflict (id) do update set
  owner_user_id = excluded.owner_user_id,
  name_th = excluded.name_th,
  name_en = excluded.name_en,
  story_th = excluded.story_th,
  story_en = excluded.story_en,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location = excluded.location,
  address_th = excluded.address_th,
  address_en = excluded.address_en,
  google_maps_url = excluded.google_maps_url,
  opening_hours = excluded.opening_hours,
  timezone = excluded.timezone,
  is_open = excluded.is_open,
  view_tags = excluded.view_tags,
  atmosphere_tags = excluded.atmosphere_tags,
  service_tags = excluded.service_tags,
  place_context_tags = excluded.place_context_tags,
  restaurant_dietary_tags = excluded.restaurant_dietary_tags,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  price_currency = excluded.price_currency,
  image_type = excluded.image_type;

insert into public.menus (
  restaurant_id,
  name_th,
  name_en,
  description_th,
  description_en,
  price,
  food_tags,
  taste_tags,
  ingredient_tags,
  allergen_tags,
  dietary_tags,
  spicy_level,
  image_type,
  ai_suggested,
  confirmed_by_restaurant
)
values
  (
    '20000000-0000-0000-0000-000000000001',
    'แกงเห็ดรวม',
    'Mixed Mushroom Curry',
    'แกงเห็ดพื้นบ้านรสเผ็ด หอมสมุนไพร ไม่มีหมูและปรับเป็นมังสวิรัติได้',
    'Spicy local mushroom curry with herbs, no pork, and vegetarian-adjustable.',
    120,
    array['thai_food', 'local_food', 'soup'],
    array['spicy', 'savory'],
    array['mushroom', 'herbs'],
    array[]::text[],
    array['no_pork', 'vegetarian_possible', 'vegan_possible'],
    3,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000001',
    'ต้มยำกุ้งแม่น้ำ',
    'River Prawn Tom Yum',
    'ต้มยำกุ้งแม่น้ำรสจัด มีข้อมูลกุ้งและอาหารทะเลชัดเจน',
    'Spicy and sour river prawn soup with clear shellfish and seafood allergy notes.',
    220,
    array['thai_food', 'soup', 'spicy', 'seafood'],
    array['spicy', 'sour'],
    array['shrimp', 'lemongrass', 'chili'],
    array['shrimp', 'seafood', 'shellfish'],
    array['contains_seafood', 'not_vegetarian'],
    4,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000001',
    'ผัดกะเพราเนื้อสับ',
    'Stir-Fried Beef Basil',
    'กะเพราเนื้อรสจัด เมนูนี้รอร้านยืนยันข้อมูลซอสและสารก่อภูมิแพ้',
    'Spicy minced beef basil. Sauce and allergen details still need restaurant confirmation.',
    140,
    array['thai_food', 'spicy', 'local_food'],
    array['spicy', 'savory'],
    array['beef', 'basil', 'soy_sauce'],
    array['soy'],
    array['contains_beef', 'not_vegetarian'],
    4,
    'placeholder',
    true,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000001',
    'ยำผักกูด',
    'Fiddlehead Fern Salad',
    'ยำผักพื้นบ้านรสเปรี้ยวเผ็ด ไม่มีหมู เหมาะกับคนอยากลองอาหารท้องถิ่น',
    'Spicy and sour local fern salad, no pork, good for tourists trying local food.',
    95,
    array['thai_food', 'local_food', 'salad'],
    array['spicy', 'sour'],
    array['local_vegetable', 'chili', 'lime'],
    array[]::text[],
    array['no_pork', 'vegetarian_possible'],
    3,
    'placeholder',
    false,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    'ก๋วยเตี๋ยวเรือหมู',
    'Pork Boat Noodles',
    'ก๋วยเตี๋ยวเรือน้ำเข้มข้นสูตรชุมชน',
    'Rich local-style pork boat noodles.',
    55,
    array['thai_food', 'noodle', 'local_food'],
    array['savory'],
    array['pork'],
    array[]::text[],
    array['contains_pork', 'not_vegetarian'],
    2,
    'placeholder',
    false,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    'ก๋วยเตี๋ยวเห็ดน้ำใส',
    'Clear Mushroom Noodles',
    'ก๋วยเตี๋ยวเห็ดน้ำใส ไม่มีหมูและราคาเข้าถึงง่าย',
    'Clear mushroom noodles with no pork and a friendly price.',
    65,
    array['thai_food', 'noodle', 'local_food'],
    array['savory'],
    array['mushroom'],
    array[]::text[],
    array['no_pork', 'vegetarian_possible'],
    1,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    'ต้มจับฉ่ายเจ',
    'Vegan Mixed Vegetable Soup',
    'ต้มจับฉ่ายเจรสอ่อน ไม่มีหมู ไม่มีเนื้อ และเหมาะกับวีแกน',
    'Mild vegan mixed vegetable soup with no pork or beef.',
    70,
    array['thai_food', 'soup', 'local_food'],
    array['savory'],
    array['vegetable', 'tofu'],
    array['soy'],
    array['no_pork', 'no_beef', 'vegetarian_possible', 'vegan_possible'],
    0,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    'ลาบเห็ดเจ',
    'Vegan Spicy Mushroom Larb',
    'ลาบเห็ดเจรสจัด หอมข้าวคั่วและสมุนไพร',
    'Spicy vegan mushroom larb with roasted rice and herbs.',
    95,
    array['thai_food', 'local_food', 'salad'],
    array['spicy', 'sour'],
    array['mushroom', 'herbs'],
    array[]::text[],
    array['no_pork', 'no_beef', 'vegetarian_possible', 'vegan_possible'],
    4,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000004',
    'ปลาย่างสมุนไพร',
    'Herb-Grilled Fish',
    'ปลาทะเลย่างสมุนไพร เสิร์ฟกับน้ำจิ้มซีฟู้ด',
    'Herb-grilled sea fish served with seafood sauce.',
    280,
    array['thai_food', 'seafood', 'local_food'],
    array['spicy', 'sour', 'savory'],
    array['fish', 'herbs'],
    array['seafood', 'fish'],
    array['contains_seafood', 'not_vegetarian'],
    3,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000004',
    'ข้าวผัดสับปะรดทะเล',
    'Seafood Pineapple Fried Rice',
    'ข้าวผัดสับปะรดใส่กุ้งและปลาหมึก เหมาะกับครอบครัว',
    'Pineapple fried rice with shrimp and squid, family friendly.',
    190,
    array['thai_food', 'seafood'],
    array['sweet', 'savory'],
    array['shrimp', 'squid', 'pineapple'],
    array['shrimp', 'seafood', 'shellfish'],
    array['contains_seafood', 'not_vegetarian'],
    1,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000005',
    'ข้าวซอยไก่',
    'Chicken Khao Soi',
    'ข้าวซอยไก่เชียงใหม่ รสเข้มข้น มีเมนูภาษาอังกฤษ',
    'Chiang Mai chicken khao soi with English menu notes.',
    95,
    array['thai_food', 'noodle', 'local_food'],
    array['spicy', 'savory'],
    array['chicken', 'coconut_milk'],
    array[]::text[],
    array['no_pork', 'not_vegetarian'],
    3,
    'placeholder',
    false,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000005',
    'ข้าวซอยเต้าหู้',
    'Tofu Khao Soi',
    'ข้าวซอยเต้าหู้ ไม่มีหมู เหมาะกับคนไม่กินเนื้อ',
    'Tofu khao soi with no pork, good for meat-free diners.',
    90,
    array['thai_food', 'noodle', 'local_food'],
    array['spicy', 'savory'],
    array['tofu', 'coconut_milk'],
    array['soy'],
    array['no_pork', 'vegetarian_possible'],
    3,
    'placeholder',
    true,
    true
  )
on conflict (restaurant_id, name_th) do update set
  name_en = excluded.name_en,
  description_th = excluded.description_th,
  description_en = excluded.description_en,
  price = excluded.price,
  food_tags = excluded.food_tags,
  taste_tags = excluded.taste_tags,
  ingredient_tags = excluded.ingredient_tags,
  allergen_tags = excluded.allergen_tags,
  dietary_tags = excluded.dietary_tags,
  spicy_level = excluded.spicy_level,
  image_type = excluded.image_type,
  ai_suggested = excluded.ai_suggested,
  confirmed_by_restaurant = excluded.confirmed_by_restaurant;

insert into public.reviews (user_id, restaurant_id, rating, review_bubbles, comment, created_at)
values
  ('10000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000001', 5, array['good_local_taste', 'friendly_staff', 'photo_spot'], '[demo_seed] รสชาติท้องถิ่นดีมาก พนักงานช่วยอธิบายเมนูเป็นภาษาอังกฤษ', now() - interval '1 day'),
  ('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000001', 4, array['good_local_taste', 'mountain_view', 'family_friendly'], '[demo_seed] วิวภูเขาดีและเหมาะกับครอบครัว แต่เมนู allergen บางจุดยังอยากให้ชัดกว่านี้', now() - interval '2 days'),
  ('10000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000001', 4, array['friendly_staff', 'menu_hard_to_understand'], '[demo_seed] อาหารอร่อย แต่รูปเมนูบางจานยังไม่มีและอ่านส่วนผสมยาก', now() - interval '3 days'),
  ('10000000-0000-0000-0000-000000000006', '20000000-0000-0000-0000-000000000001', 5, array['good_local_taste', 'clean_toilet', 'good_for_group'], '[demo_seed] กลุ่มเพื่อนชอบแกงเห็ดรวม และร้านช่วยแนะนำเมนูไม่มีหมูได้ดี', now() - interval '4 days'),
  ('10000000-0000-0000-0000-000000000007', '20000000-0000-0000-0000-000000000001', 3, array['too_far', 'parking_not_enough'], '[demo_seed] อาหารดีแต่ถ้าไม่มีรถส่วนตัวจะเดินทางยาก และที่จอดรถแน่นช่วงเย็น', now() - interval '6 days'),
  ('10000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000002', 4, array['river_view', 'good_local_taste'], '[demo_seed] ก๋วยเตี๋ยวราคาดี วิวริมน้ำน่ารัก', now() - interval '5 days'),
  ('10000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000003', 5, array['friendly_staff', 'vegetarian_friendly', 'quiet'], '[demo_seed] ร้านเงียบและมีตัวเลือกมังสวิรัติชัดเจน', now() - interval '7 days'),
  ('10000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000004', 4, array['sea_view', 'photo_spot', 'good_for_group'], '[demo_seed] วิวทะเลสวย เหมาะกับกลุ่ม แต่ราคาสูงกว่าร้านทั่วไป', now() - interval '8 days'),
  ('10000000-0000-0000-0000-000000000006', '20000000-0000-0000-0000-000000000005', 4, array['english_menu_available', 'good_local_taste'], '[demo_seed] ข้าวซอยอร่อยและอ่านเมนูภาษาอังกฤษง่าย', now() - interval '9 days');

with demo_users as (
  select unnest(array[
    '10000000-0000-0000-0000-000000000001'::uuid,
    '10000000-0000-0000-0000-000000000003'::uuid,
    '10000000-0000-0000-0000-000000000004'::uuid,
    '10000000-0000-0000-0000-000000000005'::uuid,
    '10000000-0000-0000-0000-000000000006'::uuid,
    '10000000-0000-0000-0000-000000000007'::uuid
  ]) as user_id
),
demo_restaurants as (
  select unnest(array[
    '20000000-0000-0000-0000-000000000001'::uuid,
    '20000000-0000-0000-0000-000000000002'::uuid,
    '20000000-0000-0000-0000-000000000003'::uuid,
    '20000000-0000-0000-0000-000000000004'::uuid,
    '20000000-0000-0000-0000-000000000005'::uuid
  ]) as restaurant_id
),
viewed_events as (
  select
    gen_random_uuid() as id,
    (array(select user_id from demo_users))[1 + ((gs - 1) % 6)] as user_id,
    case when gs % 7 = 0 then '30000000-0000-0000-0000-000000000001'::uuid else null::uuid end as group_id,
    case
      when gs <= 140 then '20000000-0000-0000-0000-000000000001'::uuid
      else (array(select restaurant_id from demo_restaurants))[1 + ((gs - 141) % 5)]
    end as restaurant_id,
    'viewed'::text as action,
    array[]::text[] as reject_reasons,
    null::numeric as match_score,
    jsonb_build_object(
      'demo_seed', 'true',
      'source', 'demo_funnel',
      'query', case
        when gs % 5 = 0 then 'spicy local food no pork'
        when gs % 5 = 1 then 'quiet mountain view local restaurant'
        when gs % 5 = 2 then 'vegetarian local food'
        when gs % 5 = 3 then 'seafood photo spot'
        else 'family friendly Thai food'
      end
    ) as query_context,
    '{}'::jsonb as score_breakdown,
    now() - ((gs % 29)::text || ' days')::interval - ((gs % 11)::text || ' hours')::interval as created_at
  from generate_series(1, 210) as gs
),
selected_events as (
  select
    gen_random_uuid() as id,
    (array(select user_id from demo_users))[1 + ((gs - 1) % 6)] as user_id,
    case when gs % 5 = 0 then '30000000-0000-0000-0000-000000000001'::uuid else null::uuid end as group_id,
    case
      when gs <= 52 then '20000000-0000-0000-0000-000000000001'::uuid
      else (array(select restaurant_id from demo_restaurants))[1 + ((gs - 53) % 5)]
    end as restaurant_id,
    'selected'::text as action,
    array[]::text[] as reject_reasons,
    (78 + (gs % 18))::numeric as match_score,
    jsonb_build_object('demo_seed', 'true', 'source', 'demo_selection') as query_context,
    jsonb_build_object(
      'menuScore', 42 + (gs % 8),
      'restaurantScore', 22 + (gs % 7),
      'learnedPreferenceScore', 8 + (gs % 4)
    ) as score_breakdown,
    now() - ((gs % 28)::text || ' days')::interval - ((gs % 8)::text || ' hours')::interval as created_at
  from generate_series(1, 78) as gs
),
skipped_events as (
  select
    gen_random_uuid() as id,
    (array(select user_id from demo_users))[1 + ((gs - 1) % 6)] as user_id,
    case when gs % 6 = 0 then '30000000-0000-0000-0000-000000000001'::uuid else null::uuid end as group_id,
    case
      when gs <= 32 then '20000000-0000-0000-0000-000000000001'::uuid
      else (array(select restaurant_id from demo_restaurants))[1 + ((gs - 33) % 5)]
    end as restaurant_id,
    'skipped'::text as action,
    case gs % 6
      when 0 then array['not_safe_allergy']
      when 1 then array['too_far']
      when 2 then array['menu_hard_to_understand']
      when 3 then array['too_expensive']
      when 4 then array['parking_not_enough']
      else array['not_enough_vegetarian_options']
    end as reject_reasons,
    (55 + (gs % 18))::numeric as match_score,
    jsonb_build_object(
      'demo_seed', 'true',
      'source', 'demo_skip',
      'selectedBubble', case gs % 6
        when 0 then 'not_safe_allergy'
        when 1 then 'too_far'
        when 2 then 'menu_hard_to_understand'
        when 3 then 'too_expensive'
        when 4 then 'parking_not_enough'
        else 'not_enough_vegetarian_options'
      end
    ) as query_context,
    jsonb_build_object(
      'menuScore', 25 + (gs % 8),
      'restaurantScore', 17 + (gs % 6),
      'riskPenalty', 8 + (gs % 9)
    ) as score_breakdown,
    now() - ((gs % 27)::text || ' days')::interval - ((gs % 10)::text || ' hours')::interval as created_at
  from generate_series(1, 56) as gs
)
insert into public.match_histories (
  id,
  user_id,
  group_id,
  restaurant_id,
  action,
  reject_reasons,
  match_score,
  query_context,
  score_breakdown,
  created_at
)
select * from viewed_events
union all
select * from selected_events
union all
select * from skipped_events;

commit;
