insert into public.users (id, name, language, nationality)
values
  ('10000000-0000-0000-0000-000000000001', 'Demo Tourist', 'en', 'United States'),
  ('10000000-0000-0000-0000-000000000002', 'เจ้าของร้านเดโม', 'th', 'Thailand')
on conflict (id) do nothing;

insert into public.user_preferences (
  user_id,
  food_tags,
  view_tags,
  atmosphere_tags,
  service_tags,
  place_context_tags,
  dietary_restrictions,
  allergies,
  transport_modes,
  budget_min,
  budget_max,
  max_distance_km,
  learned_preferences
)
values (
  '10000000-0000-0000-0000-000000000001',
  array['thai_food', 'local_food', 'spicy'],
  array['mountain_view', 'river_view'],
  array['quiet', 'hidden_gem'],
  array['english_menu_available', 'tourist_friendly'],
  array['local_hidden_gem', 'good_for_group'],
  array['no_pork'],
  array['shrimp'],
  array['taxi', 'walking', 'public_transit'],
  50,
  250,
  15,
  '{"tagWeights": {"local_food": 1.2, "quiet": 1.1}}'::jsonb
)
on conflict (user_id) do nothing;

insert into public.tag_catalogs (
  category,
  tag_key,
  label_th,
  label_en,
  description_th,
  description_en
)
values
  ('food', 'thai_food', 'อาหารไทย', 'Thai food', 'อาหารไทยทั่วไป', 'General Thai cuisine'),
  ('food', 'local_food', 'อาหารท้องถิ่น', 'Local food', 'อาหารพื้นถิ่นหรือสูตรชุมชน', 'Local or community-style food'),
  ('food', 'noodle', 'ก๋วยเตี๋ยว', 'Noodle', 'เมนูเส้น', 'Noodle dishes'),
  ('food', 'seafood', 'อาหารทะเล', 'Seafood', 'อาหารจากทะเล', 'Seafood dishes'),
  ('food', 'soup', 'ซุป', 'Soup', 'เมนูน้ำแกงหรือต้ม', 'Soup dishes'),
  ('taste', 'spicy', 'เผ็ด', 'Spicy', 'รสเผ็ด', 'Spicy taste'),
  ('taste', 'sour', 'เปรี้ยว', 'Sour', 'รสเปรี้ยว', 'Sour taste'),
  ('taste', 'sweet', 'หวาน', 'Sweet', 'รสหวาน', 'Sweet taste'),
  ('taste', 'savory', 'กลมกล่อม', 'Savory', 'รสเค็มมันหรือกลมกล่อม', 'Savory taste'),
  ('ingredient', 'shrimp', 'กุ้ง', 'Shrimp', 'มีหรือเกี่ยวข้องกับกุ้ง', 'Contains or relates to shrimp'),
  ('ingredient', 'pork', 'หมู', 'Pork', 'มีหรือเกี่ยวข้องกับหมู', 'Contains or relates to pork'),
  ('ingredient', 'beef', 'เนื้อวัว', 'Beef', 'มีหรือเกี่ยวข้องกับเนื้อวัว', 'Contains or relates to beef'),
  ('ingredient', 'chicken', 'ไก่', 'Chicken', 'มีหรือเกี่ยวข้องกับไก่', 'Contains or relates to chicken'),
  ('ingredient', 'mushroom', 'เห็ด', 'Mushroom', 'มีเห็ด', 'Contains mushroom'),
  ('ingredient', 'peanut', 'ถั่วลิสง', 'Peanut', 'มีหรือเกี่ยวข้องกับถั่วลิสง', 'Contains or relates to peanut'),
  ('ingredient', 'coconut_milk', 'กะทิ', 'Coconut milk', 'มีกะทิ', 'Contains coconut milk'),
  ('allergen', 'shrimp', 'แพ้กุ้ง', 'Shrimp allergy', 'ควรระวังสำหรับผู้แพ้กุ้ง', 'Risk for shrimp allergy'),
  ('allergen', 'seafood', 'แพ้อาหารทะเล', 'Seafood allergy', 'ควรระวังสำหรับผู้แพ้อาหารทะเล', 'Risk for seafood allergy'),
  ('allergen', 'peanut', 'แพ้ถั่วลิสง', 'Peanut allergy', 'ควรระวังสำหรับผู้แพ้ถั่วลิสง', 'Risk for peanut allergy'),
  ('dietary', 'contains_pork', 'มีหมู', 'Contains pork', 'เมนูมีหมู', 'Menu contains pork'),
  ('dietary', 'contains_beef', 'มีเนื้อวัว', 'Contains beef', 'เมนูมีเนื้อวัว', 'Menu contains beef'),
  ('dietary', 'contains_seafood', 'มีอาหารทะเล', 'Contains seafood', 'เมนูมีอาหารทะเล', 'Menu contains seafood'),
  ('dietary', 'no_pork', 'ไม่มีหมู', 'No pork', 'เมนูไม่มีหมู', 'Menu has no pork'),
  ('dietary', 'no_beef', 'ไม่มีเนื้อวัว', 'No beef', 'เมนูไม่มีเนื้อวัว', 'Menu has no beef'),
  ('dietary', 'vegetarian_possible', 'ทำมังสวิรัติได้', 'Vegetarian possible', 'ร้านอาจปรับเป็นมังสวิรัติได้', 'May be adjustable for vegetarian diet'),
  ('dietary', 'vegan_possible', 'ทำวีแกนได้', 'Vegan possible', 'ร้านอาจปรับเป็นวีแกนได้', 'May be adjustable for vegan diet'),
  ('dietary', 'halal_possible', 'อาจทำฮาลาลได้', 'Halal possible', 'ต้องยืนยันกับร้านก่อน', 'Requires restaurant confirmation'),
  ('dietary', 'not_vegetarian', 'ไม่ใช่มังสวิรัติ', 'Not vegetarian', 'เมนูนี้ไม่เหมาะกับมังสวิรัติ', 'Not suitable for vegetarian diet'),
  ('view', 'mountain_view', 'วิวภูเขา', 'Mountain view', 'เห็นภูเขาหรือธรรมชาติ', 'Mountain or nature view'),
  ('view', 'river_view', 'วิวแม่น้ำ', 'River view', 'เห็นแม่น้ำหรือลำคลอง', 'River or canal view'),
  ('view', 'sea_view', 'วิวทะเล', 'Sea view', 'เห็นทะเล', 'Sea view'),
  ('atmosphere', 'quiet', 'เงียบสงบ', 'Quiet', 'บรรยากาศไม่วุ่นวาย', 'Quiet atmosphere'),
  ('atmosphere', 'family_friendly', 'เหมาะกับครอบครัว', 'Family friendly', 'เหมาะกับเด็กหรือครอบครัว', 'Good for families'),
  ('atmosphere', 'photo_spot', 'ถ่ายรูปสวย', 'Photo spot', 'เหมาะกับการถ่ายรูป', 'Good photo spot'),
  ('service', 'english_menu_available', 'มีเมนูภาษาอังกฤษ', 'English menu available', 'ร้านมีเมนูภาษาอังกฤษ', 'Restaurant has an English menu'),
  ('service', 'tourist_friendly', 'เป็นมิตรกับนักท่องเที่ยว', 'Tourist friendly', 'ร้านเหมาะกับนักท่องเที่ยว', 'Friendly to tourists'),
  ('service', 'cash_only', 'รับเงินสดเท่านั้น', 'Cash only', 'ร้านรับเฉพาะเงินสด', 'Restaurant accepts cash only'),
  ('service', 'promptpay_available', 'รับพร้อมเพย์', 'PromptPay available', 'ร้านรับพร้อมเพย์', 'Restaurant accepts PromptPay'),
  ('service', 'parking_available', 'มีที่จอดรถ', 'Parking available', 'ร้านมีที่จอดรถ', 'Parking is available'),
  ('service', 'card_accepted', 'รับบัตร', 'Card accepted', 'ร้านรับบัตรเครดิตหรือเดบิต', 'Restaurant accepts credit or debit cards'),
  ('service', 'friendly_staff', 'พนักงานเป็นมิตร', 'Friendly staff', 'บริการเป็นกันเอง', 'Friendly service'),
  ('place_context', 'hidden_gem', 'ร้านลับ', 'Hidden gem', 'ไม่ใช่ร้านกระแสหลัก', 'Less obvious local place'),
  ('place_context', 'local_hidden_gem', 'ร้านลับท้องถิ่น', 'Local hidden gem', 'ร้านท้องถิ่นที่ไม่ค่อยอยู่ในเส้นทางหลัก', 'A less obvious local restaurant'),
  ('place_context', 'good_for_group', 'เหมาะกับกลุ่ม', 'Good for group', 'รองรับการมากันหลายคน', 'Good for groups'),
  ('transport', 'walking', 'เดิน', 'Walking', 'เดินจากตำแหน่งปัจจุบัน', 'Walk from current location'),
  ('transport', 'driving', 'รถยนต์', 'Driving', 'เดินทางด้วยรถยนต์', 'Travel by car'),
  ('transport', 'motorbike', 'มอเตอร์ไซค์', 'Motorbike', 'เดินทางด้วยมอเตอร์ไซค์', 'Travel by motorbike'),
  ('transport', 'public_transit', 'ขนส่งสาธารณะ', 'Public transit', 'เดินทางด้วยรถโดยสารหรือระบบขนส่งสาธารณะ', 'Travel by public transportation'),
  ('transport', 'taxi', 'แท็กซี่', 'Taxi', 'เดินทางด้วยแท็กซี่หรือรถเรียกผ่านแอป', 'Travel by taxi or ride-hailing'),
  ('review_bubble', 'good_local_taste', 'รสชาติท้องถิ่นดี', 'Good local taste', 'นักท่องเที่ยวชอบรสชาติท้องถิ่น', 'Tourists liked the local taste'),
  ('review_bubble', 'too_far', 'ไกลเกินไป', 'Too far', 'ระยะทางเป็นปัญหา', 'Distance was a problem'),
  ('review_bubble', 'menu_hard_to_understand', 'เมนูเข้าใจยาก', 'Menu hard to understand', 'นักท่องเที่ยวอ่านเมนูลำบาก', 'Tourists had trouble understanding the menu'),
  ('review_bubble', 'not_clean', 'ไม่สะอาด', 'Not clean', 'มีข้อกังวลด้านความสะอาด', 'Cleanliness concern'),
  ('review_bubble', 'friendly_staff', 'พนักงานเป็นมิตร', 'Friendly staff', 'บริการเป็นมิตร', 'Friendly staff'),
  ('skip_reason', 'too_far', 'ไกลเกินไป', 'Too far', 'ผู้ใช้ข้ามเพราะไกล', 'Skipped because too far'),
  ('skip_reason', 'too_expensive', 'แพงเกินไป', 'Too expensive', 'ผู้ใช้ข้ามเพราะราคาเกินงบ', 'Skipped because over budget'),
  ('skip_reason', 'not_safe_allergy', 'ไม่มั่นใจเรื่องแพ้อาหาร', 'Allergy concern', 'ผู้ใช้ข้ามเพราะกังวล allergen', 'Skipped due to allergy concern')
on conflict (category, tag_key) do update set
  label_th = excluded.label_th,
  label_en = excluded.label_en,
  description_th = excluded.description_th,
  description_en = excluded.description_en,
  is_active = true;

insert into public.menu_dictionary (
  menu_name_th,
  menu_name_en,
  food_tags,
  taste_tags,
  ingredient_tags,
  allergen_tags,
  dietary_tags,
  spicy_level,
  confidence
)
values
  (
    'ต้มยำกุ้ง',
    'Tom Yum Kung',
    array['thai_food', 'soup', 'spicy', 'seafood'],
    array['spicy', 'sour'],
    array['shrimp'],
    array['shrimp', 'seafood'],
    array['contains_seafood', 'not_vegetarian'],
    4,
    0.940
  ),
  (
    'ผัดไทย',
    'Pad Thai',
    array['thai_food', 'noodle'],
    array['sweet', 'savory'],
    array['shrimp', 'peanut'],
    array['shrimp', 'peanut'],
    array['contains_seafood'],
    1,
    0.890
  ),
  (
    'แกงเขียวหวานไก่',
    'Green Curry Chicken',
    array['thai_food', 'spicy'],
    array['spicy', 'savory'],
    array['chicken', 'coconut_milk'],
    array[]::text[],
    array['no_pork'],
    3,
    0.860
  ),
  (
    'แกงเห็ดรวม',
    'Mixed Mushroom Curry',
    array['thai_food', 'local_food', 'soup'],
    array['spicy', 'savory'],
    array['mushroom'],
    array[]::text[],
    array['no_pork', 'vegetarian_possible'],
    3,
    0.820
  )
on conflict (menu_name_th) do update set
  menu_name_en = excluded.menu_name_en,
  food_tags = excluded.food_tags,
  taste_tags = excluded.taste_tags,
  ingredient_tags = excluded.ingredient_tags,
  allergen_tags = excluded.allergen_tags,
  dietary_tags = excluded.dietary_tags,
  spicy_level = excluded.spicy_level,
  confidence = excluded.confidence;

insert into public.restaurants (
  id,
  owner_user_id,
  name_th,
  name_en,
  story_th,
  story_en,
  latitude,
  longitude,
  location,
  address_th,
  address_en,
  google_maps_url,
  google_place_id,
  opening_hours,
  timezone,
  is_open,
  view_tags,
  atmosphere_tags,
  service_tags,
  place_context_tags,
  restaurant_dietary_tags,
  price_min,
  price_max,
  price_currency,
  image_type
)
values
  (
    '20000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000002',
    'ครัวบ้านสวน',
    'Baan Suan Kitchen',
    'ร้านอาหารท้องถิ่นในสวนใกล้เนินเขา ใช้วัตถุดิบจากชุมชน',
    'A local garden kitchen near the hills using community ingredients.',
    18.7883,
    98.9853,
    st_setsrid(st_makepoint(98.9853, 18.7883), 4326)::geography,
    'อำเภอเมืองเชียงใหม่ จังหวัดเชียงใหม่',
    'Mueang Chiang Mai District, Chiang Mai',
    'https://maps.google.com/?q=18.7883,98.9853',
    null,
    '[{"day":"mon","open":"09:00","close":"20:00"},{"day":"tue","open":"09:00","close":"20:00"},{"day":"wed","open":"09:00","close":"20:00"},{"day":"thu","open":"09:00","close":"20:00"},{"day":"fri","open":"09:00","close":"20:00"},{"day":"sat","open":"09:00","close":"21:00"},{"day":"sun","open":"09:00","close":"21:00"}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['mountain_view'],
    array['quiet', 'family_friendly'],
    array['friendly_staff', 'english_menu_available', 'parking_available', 'promptpay_available'],
    array['hidden_gem', 'local_hidden_gem', 'good_for_group'],
    array['vegetarian_friendly', 'vegan_friendly'],
    60,
    220,
    'THB',
    'placeholder'
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000002',
    'ริมน้ำก๋วยเตี๋ยวเรือ',
    'Rim Nam Boat Noodles',
    'ร้านก๋วยเตี๋ยวริมคลองในย่านชุมชนเก่า',
    'A canal-side noodle shop in an old local neighborhood.',
    13.7563,
    100.5018,
    st_setsrid(st_makepoint(100.5018, 13.7563), 4326)::geography,
    'เขตพระนคร กรุงเทพมหานคร',
    'Phra Nakhon District, Bangkok',
    'https://maps.google.com/?q=13.7563,100.5018',
    null,
    '[{"day":"mon","open":"10:00","close":"18:00"},{"day":"tue","open":"10:00","close":"18:00"},{"day":"wed","open":"10:00","close":"18:00"},{"day":"thu","open":"10:00","close":"18:00"},{"day":"fri","open":"10:00","close":"18:00"},{"day":"sat","open":"10:00","close":"18:00"},{"day":"sun","closed":true}]'::jsonb,
    'Asia/Bangkok',
    true,
    array['river_view'],
    array['quiet'],
    array['friendly_staff', 'cash_only', 'tourist_friendly'],
    array['hidden_gem', 'local_hidden_gem'],
    array[]::text[],
    40,
    120,
    'THB',
    'placeholder'
  )
on conflict (id) do nothing;

insert into public.menus (
  restaurant_id,
  name_th,
  name_en,
  description_th,
  description_en,
  price,
  food_tags,
  taste_tags,
  ingredient_tags,
  allergen_tags,
  dietary_tags,
  spicy_level,
  image_type,
  ai_suggested,
  confirmed_by_restaurant
)
values
  (
    '20000000-0000-0000-0000-000000000001',
    'แกงเห็ดรวม',
    'Mixed Mushroom Curry',
    'แกงเห็ดพื้นบ้านรสเผ็ด หอมสมุนไพร',
    'Spicy local mushroom curry with aromatic herbs.',
    120,
    array['thai_food', 'local_food', 'soup'],
    array['spicy', 'savory'],
    array['mushroom'],
    array[]::text[],
    array['no_pork', 'vegetarian_possible'],
    3,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000001',
    'ต้มยำกุ้ง',
    'Tom Yum Kung',
    'ต้มยำกุ้งน้ำใสรสจัด',
    'Clear spicy and sour shrimp soup.',
    180,
    array['thai_food', 'soup', 'spicy', 'seafood'],
    array['spicy', 'sour'],
    array['shrimp'],
    array['shrimp', 'seafood'],
    array['contains_seafood', 'not_vegetarian'],
    4,
    'placeholder',
    true,
    true
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    'ก๋วยเตี๋ยวเรือหมู',
    'Pork Boat Noodles',
    'ก๋วยเตี๋ยวเรือน้ำเข้มข้นสูตรชุมชน',
    'Rich local-style pork boat noodles.',
    55,
    array['thai_food', 'noodle', 'local_food'],
    array['savory'],
    array['pork'],
    array[]::text[],
    array['contains_pork', 'not_vegetarian'],
    2,
    'placeholder',
    false,
    true
  )
on conflict (restaurant_id, name_th) do update set
  name_en = excluded.name_en,
  description_th = excluded.description_th,
  description_en = excluded.description_en,
  price = excluded.price,
  food_tags = excluded.food_tags,
  taste_tags = excluded.taste_tags,
  ingredient_tags = excluded.ingredient_tags,
  allergen_tags = excluded.allergen_tags,
  dietary_tags = excluded.dietary_tags,
  spicy_level = excluded.spicy_level,
  image_type = excluded.image_type,
  ai_suggested = excluded.ai_suggested,
  confirmed_by_restaurant = excluded.confirmed_by_restaurant;
